/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Audio {
  static fromFile(path: string): Audio
  static fromBuffer(buffer: Buffer): Audio
  get title(): string | null
  get artist(): string | null
  get album(): string | null
  get genre(): string | null
  set title(title: string)
  set artist(artist: string)
  set album(album: string)
  set genre(genre: string)
  buffer(): Buffer
  save(path: string): void
}
